[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python game_server.py --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "redis"
